version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    container_name: deunaDB
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: deunaDB
    ports:
      - 5432:5432
    volumes:
      - ./postgress:/var/lib/postgresql/data
      - ./initialDeUnaDB.sql:/docker-entrypoint-initdb.d/initialDeUnaDB.sql